[build]
  publish = "."

[[headers]]
  for = "/inventory.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "/inventory"
  to = "/inventory.html"
  status = 200

[[redirects]]
  from = "/software"
  to = "/software.html"
  status = 200
